name: Send Email via SMTP

on: [push]

jobs:
  send_email:
    runs-on: ubuntu-latest
    environment: email_credentials
    steps:
      - name: Checkout code
        uses: actions/checkout@v2 

      - name: list dir
        run: cd scripts && ls -l
        
      - name: Install and Send Email
        run: |
          sudo bash scripts/email_alert.sh "smtp.gmail.com" "gmail.com" "${{ secrets.AuthUser }}" "${{ secrets.AuthPass }}" "Hello, this is the body of the email." "Email Subject" "Testing!"