name: Send Email via SMTP

on: [push]

env:
  workdir: "scripts/"
jobs:
  send_email:
    runs-on: ubuntu-latest
    environment: email_credentials
    steps:
      - name: Checkout code
        uses: actions/checkout@v2 

      - name: Check current directory and list files
        run: |
            pwd
            ls -l

      - name: Install and Send Email
        run: |
          cd ${{ env.workdir }} && sudo chmod +x email_alert.sh
          cd ${{ env.workdir }} && sudo bash email_alert.sh "smtp.gmail.com" "gmail.com" "${{ secrets.AuthUser }}" "${{ secrets.AuthPass }}" "Hello, this is the body of the email." "Email Subject" "${{ secrets.AuthUser }}"