name: Send Email via SMTP
on:
  push:
    branches:
      - main
      - dev

env:
  workdir: "${{ github.workspace }}/scripts"
jobs:
  send_email:
    runs-on: gh-runner-dev-01
    steps:
      - name: Checkout code
        uses: actions/checkout@v2 

      - name: Check current directory and list files
        run: |
            pwd
            ls -l

      - name: Install and Send Email
        run: |
          sudo chmod +x email_alert.sh
          sudo bash email_alert.sh "${{ secrets.AuthPass }}" "Hello, this is the body of the email." "Email Subject" "labenagha@gmail.com"
        working-directory: ./scripts